# Generated by Django 6.0.4 on 2026-04-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_refs/'),
        ),
    ]
