# Generated by Django 6.0.4 on 2026-04-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_reference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_image',
            field=models.ImageField(default='', upload_to='order_refs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='screenshot',
            field=models.ImageField(default='', upload_to='payment_proofs/'),
            preserve_default=False,
        ),
    ]
