# Generated by Django 6.0.4 on 2026-04-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_reference_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alt_phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
