# Generated by Django 6.0.4 on 2026-04-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_alt_phone_number_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.CharField(blank=True, choices=[('printing', 'Printing'), ('binding', 'Binding'), ('lamination', 'Lamination'), ('photocopy', 'Photocopy'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
